name: demo_json_api
url: "https://jsonplaceholder.typicode.com/posts/{post_id}"
type: json_api

headers:
  Accept: "application/json"

extract:
  id:
    path: "$.id"
  user_id:
    path: "$.userId"
  title:
    path: "$.title"
    transform: strip
  body:
    path: "$.body"
    transform: strip
